// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.6.1
// source: tts/v1/schema.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCloudMindsTTSGetVersion = "/schema.CloudMindsTTS/GetVersion"

type CloudMindsTTSHTTPServer interface {
	GetVersion(context.Context, *VerReq) (*VerRsp, error)
}

func RegisterCloudMindsTTSHTTPServer(s *http.Server, srv CloudMindsTTSHTTPServer) {
	r := s.Route("/")
	r.GET("/speech/tts/getVersion", _CloudMindsTTS_GetVersion1_HTTP_Handler(srv))
}

func _CloudMindsTTS_GetVersion1_HTTP_Handler(srv CloudMindsTTSHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudMindsTTSGetVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVersion(ctx, req.(*VerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerRsp)
		return ctx.Result(200, reply)
	}
}

type CloudMindsTTSHTTPClient interface {
	GetVersion(ctx context.Context, req *VerReq, opts ...http.CallOption) (rsp *VerRsp, err error)
}

type CloudMindsTTSHTTPClientImpl struct {
	cc *http.Client
}

func NewCloudMindsTTSHTTPClient(client *http.Client) CloudMindsTTSHTTPClient {
	return &CloudMindsTTSHTTPClientImpl{client}
}

func (c *CloudMindsTTSHTTPClientImpl) GetVersion(ctx context.Context, in *VerReq, opts ...http.CallOption) (*VerRsp, error) {
	var out VerRsp
	pattern := "/speech/tts/getVersion"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCloudMindsTTSGetVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
