// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v3.6.1
// source: tts/v2/tts.proto

package v2

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCloudMindsTTSGetTtsConfig = "/ttsschema.CloudMindsTTS/GetTtsConfig"
const OperationCloudMindsTTSGetVersion = "/ttsschema.CloudMindsTTS/GetVersion"
const OperationCloudMindsTTSRegister = "/ttsschema.CloudMindsTTS/Register"

type CloudMindsTTSHTTPServer interface {
	// GetTtsConfig 获取服务端配置信息
	GetTtsConfig(context.Context, *VerReq) (*RespGetTtsConfig, error)
	// GetVersion 获取服务版本信息
	GetVersion(context.Context, *VerVersionReq) (*VerVersionRsp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
}

func RegisterCloudMindsTTSHTTPServer(s *http.Server, srv CloudMindsTTSHTTPServer) {
	r := s.Route("/")
	r.GET("/speech/tts/getVersion", _CloudMindsTTS_GetVersion0_HTTP_Handler(srv))
	r.GET("/speech/tts/getConfig", _CloudMindsTTS_GetTtsConfig0_HTTP_Handler(srv))
	r.POST("/speech/tts/register", _CloudMindsTTS_Register0_HTTP_Handler(srv))
}

func _CloudMindsTTS_GetVersion0_HTTP_Handler(srv CloudMindsTTSHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerVersionReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudMindsTTSGetVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVersion(ctx, req.(*VerVersionReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerVersionRsp)
		return ctx.Result(200, reply)
	}
}

func _CloudMindsTTS_GetTtsConfig0_HTTP_Handler(srv CloudMindsTTSHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudMindsTTSGetTtsConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTtsConfig(ctx, req.(*VerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RespGetTtsConfig)
		return ctx.Result(200, reply)
	}
}

func _CloudMindsTTS_Register0_HTTP_Handler(srv CloudMindsTTSHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCloudMindsTTSRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterResp)
		return ctx.Result(200, reply)
	}
}

type CloudMindsTTSHTTPClient interface {
	GetTtsConfig(ctx context.Context, req *VerReq, opts ...http.CallOption) (rsp *RespGetTtsConfig, err error)
	GetVersion(ctx context.Context, req *VerVersionReq, opts ...http.CallOption) (rsp *VerVersionRsp, err error)
	Register(ctx context.Context, req *RegisterReq, opts ...http.CallOption) (rsp *RegisterResp, err error)
}

type CloudMindsTTSHTTPClientImpl struct {
	cc *http.Client
}

func NewCloudMindsTTSHTTPClient(client *http.Client) CloudMindsTTSHTTPClient {
	return &CloudMindsTTSHTTPClientImpl{client}
}

func (c *CloudMindsTTSHTTPClientImpl) GetTtsConfig(ctx context.Context, in *VerReq, opts ...http.CallOption) (*RespGetTtsConfig, error) {
	var out RespGetTtsConfig
	pattern := "/speech/tts/getConfig"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCloudMindsTTSGetTtsConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CloudMindsTTSHTTPClientImpl) GetVersion(ctx context.Context, in *VerVersionReq, opts ...http.CallOption) (*VerVersionRsp, error) {
	var out VerVersionRsp
	pattern := "/speech/tts/getVersion"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCloudMindsTTSGetVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CloudMindsTTSHTTPClientImpl) Register(ctx context.Context, in *RegisterReq, opts ...http.CallOption) (*RegisterResp, error) {
	var out RegisterResp
	pattern := "/speech/tts/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCloudMindsTTSRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
