server:
  http:
    addr: 0.0.0.0:4012
    timeout: 1s
  grpc:
    addr: 0.0.0.0:3012
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  app:
    path: ./res
  otel:
    addr: 172.16.24.200:32672
    name: speech.tts
  nacos:
    addr: nacos.region-dev-2.service.iamidata.com
    port: 31684
    contextPath: /nacos
    namespaceId: 0021fbf85038b162b3d43794a1944bde39680a5d
    group: speech-tts-86
    timeoutMs: 5000
    notLoadCacheAtStart: true
    logDir: ./runtime/nacos-logs
    cacheDir: ./runtime/nacos-cache
    logLevel: debug

log:
  root_path: runtime/
  save_path: logs/
  save_filename: log
  time_format: 2006-01-02
  max_size: 50
  max_backups: 10
  max_days: 30
  compress: false
  json_format: false
  show_line: true
  log_in_console: true
  level: debug


