package utils

var SpeakerMap = map[string]string{
	"daxiaofang_chinese_mandarin_female_adult": "DaXiaoFang",
	"daxiaoqi_chinese_mandarin_female_adult":   "DaXiaoQi",
	"dadaqiang_chinese_mandarin_male_adult":    "DaDaQiang",
	"dadagang_chinese_mandarin_male_adult":     "DaDaGang",
	"datongtong_chinese_mandarin_female_child": "DaTongTong",
	"damingming_chinese_mandarin_male_child":   "DaMingMing",
	"daxiaochuan_chinese_sichuan_female_adult": "DaXiaoChuan",
	"daxiaoyue_chinese_yueyu_female_adult":     "DaXiaoYue",
	"daxiaobei_chinese_dongbei_female_adult":   "DaXiaoBei",
	"daxiaotai_chinese_taiwan_female_adult":    "DaXiaoTai",
	"dadaxiang_chinese_hunan_male_adult":       "DaDaXiang",
	"daxiaohu_chinese_shanghai_female_adult":   "DaXiaoHu",
	"daxiaoguan_english_female_adult":          "DaXiaoguan",
	"daxiaobo_emotions_female_adult":           "DaXiaoBo",
	"daxiaowu_chinese_mandarin_female_adult":   "DaXiaoWu",
	"daxiaotong_chinese_mandarin_female_child": "DaXiaoTong",
	"dayitao_chinese_mandarin_female_child":    "DaYiTao",
	"dayimo_chinese_mandarin_male_adult":       "DaYiMo",
	"dayiqiao_chinese_mandarin_male_adult":     "DaYiQiao",
	"dayixing_chinese_mandarin_male_adult":     "DaYiXing",
	"dayiya_chinese_mandarin_male_adult":       "DaYiYa",
	"dasiqi_chinese_mandarin_female_adult":     "DaSiQi",
	"dasimo_chinese_mandarin_female_adult":     "DaSiMo",
	"dasiyuan_chinese_mandarin_female_adult":   "DaSiYuan",
	"dasiru_chinese_mandarin_female_adult":     "DaSiRu",
	"dasirou_chinese_mandarin_female_adult":    "DaSiRou",
	"dasiyue_chinese_mandarin_female_adult":    "DaSiYue",
	"dasiwei_chinese_mandarin_female_adult":    "DaSiWei",
	"dayihui_chinese_mandarin_male_adult":      "DaYiHui",
	"dasihui_chinese_mandarin_female_adult":    "DaSiHui",
	"dayibu_chinese_mandarin_female_adult":     "DaYiBu",
	"daxiaoxin_chinese_mandarin_male_child":    "DaXiaoXin",
	"dayijiang_chinese_mandarin_male_adult":    "DaYiJiang",
	"dayiwei_chinese_mandarin_male_adult":      "DaYiWei",
	"dayihao_chinese_mandarin_male_adult":      "DaYiHao",
	"dayilun_chinese_mandarin_male_adult":      "DaYiLun",
	"dayiyun_chinese_mandarin_male_adult":      "Dayiyun",
	"dasixian_chinese_mandarin_female_adult":   "DaSiXian",
	"dasimao_chinese_mandarin_female_adult":    "DaSiMao",
	"dasimei_chinese_mandarin_female_adult":    "DaSiMei",
	"dasiyun_chinese_mandarin_female_adult":    "DaSiYun",
	"dasijuan_chinese_mandarin_female_adult":   "DaSiJuan",
	"dasiting_chinese_mandarin_female_adult":   "DaSiTing",
	"dasixing_chinese_mandarin_female_adult":   "DaSiXing",
	"dasilan_chinese_mandarin_female_adult":    "DaSiLan",
	"dasijun_chinese_mandarin_female_adult":    "DaSiJun",
	"dasiqian_chinese_mandarin_female_adult":   "DaSiQian",
	"dasixue_chinese_mandarin_female_adult":    "DaSiXue",
	"dayimin_chinese_mandarin_male_adult":      "DaYiMin",
	"dayitao_chinese_mandarin_male_adult":      "DaYiTao",
	"daxiaobao_chinese_mandarin_female_child":  "DaXiaoBao",
	"doctorzhao_chinese_mandarin_male_adult":   "DoctorZhao",
}

const DefaultUser = "cloudminds"
